// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/go-chi/chi"
	"github.com/thejasn/tester/domain/flow/repo"
	repo2 "github.com/thejasn/tester/domain/testcase/repo"
	"github.com/thejasn/tester/service"
	"github.com/thejasn/tester/transport/http"
	"github.com/thejasn/tester/transport/http/handler"
	"gorm.io/gorm"
)

// Injectors from inject_tester.go:

func injectTester(ctx context.Context, r *chi.Mux, db *gorm.DB) http.Router {
	flow := repo.NewFlowRepo(db)
	testcase := repo2.NewTestcaseRepo(db)
	serviceFlow := service.NewFlowSvc(flow, testcase)
	flowhandler := handler.NewFlowHandler(serviceFlow)
	serviceTestcase := service.NewTestcaseSvc(testcase)
	testcasehandler := handler.NewTestcaseHandler(serviceTestcase)
	set := handler.Set{
		Flow:     flowhandler,
		Testcase: testcasehandler,
	}
	router := http.NewRouter(r, set)
	return router
}
